### ISSUE TITLE
Declaration?

### ISSUE THREAD

**Issue by ninjagolloyd** [TropicSapling/PBTL#1]
Where does it say how do compile (i.e. How to print?)

**Comment by TropicSapling** [comment]
um well look at the "hello world.pbtl" file for info about how to print and just run the file "compile.bat" to compile it :)

**Comment by ninjagolloyd** [comment]
But how does it know what to do?

**Comment by TropicSapling** [comment]
It just compiles it to Python actually, then you need to run it using Python compiler. But I'll fix a direct compiler later :)

**Comment by ninjagolloyd** [comment]
How does it compile to Python? How does it know what commands to use?

@TropicSapling

**Comment by TropicSapling** [comment]
um... well, just look at the file [compiler.py](https://github.com/TropicSapling/PBTL/blob/master/Python/compiler.py) :)

**Comment by ninjagolloyd** [comment]
I have not found where it uses foundPrint

**Comment by TropicSapling** [comment]
Um well just look closely, I know it is there :)

**Comment by ninjagolloyd** [comment]
Found it

**Comment by TropicSapling** [comment]
@ninjagolloyd Ok good :D
